### ISSUE TITLE
Mamba returns 0 when installations with pip fail

### ISSUE THREAD

**Issue by chrisburr** [QuantStack/mamba#299]
Using the following environment file (constructed to be unsatisfiable for pip and therefore fail):

```yaml
channels:
  - conda-forge
  - defaults

dependencies:
  - python =2.7
  - pip
  - pip:
    - matplotlib >3
```

Conda returns `1` when an environment is created from this file however mamba returns `0`:

```bash
(base) bash-5.0$ mamba --version
mamba 0.2.12
conda 4.8.3
(base) bash-5.0$ mamba env create --file environment.yaml --name test-mamba
[TRUNCATED]
ERROR: No matching distribution found for matplotlib>3 (from -r .....requirements.txt (line 1))

CondaEnvException: Pip failed
(base) bash-5.0$ echo $?
0
```
