### ISSUE TITLE
sha256 sum check fail on travis

### ISSUE THREAD

**Issue by dzelge** [QuantStack/mamba#301]
## Behaviour

When using mamba on travis I get teh follwoing error for random packages:

```
ERROR   transaction.cpp:72 File not valid: SHA256 sum doesn't match expectation "/home/travis/miniconda/pkgs/pandas-1.0.3-py37h0da4684_1.tar.bz2"
```
![image](https://user-images.githubusercontent.com/42441761/83043468-36bf9680-a043-11ea-8a80-5737bb320583.png)

As I said, the packages affected are random. When I restart the travis job other packages fail with the same message.

EDIT: 

I hope, you can see the full stack [here](https://travis-ci.com/github/dcs4cop/xcube-sh/builds/168512260)

## To reproduce

This .travis.yml should reproduce it:

```yaml

language: bash

os:
  - linux
#  - osx
#  - windows

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda install -y mamba -c conda-forge
  - conda info
  - mamba create -y -n xcube -c conda-forge xcube
```
